debug : 
	cd helloLibrary && make -f makefile.lnx CONFIG=debug
	cd Applications/Tests/helloLibrary && make -f makefile.lnx CONFIG=debug

release :
	cd helloLibrary && make -f makefile.lnx CONFIG=release
	cd Applications/Tests/helloLibrary && make -f makefile.lnx CONFIG=release
	# cd Documentation && make -f makefile

clean :
	cd helloLibraryh && make clean -f makefile.lnx
	cd Applications/Tests/helloLibrary && make clean -f makefile.lnx
